### ISSUE TITLE
Klara will not start

### ISSUE THREAD

**Issue by IM-studios** [ST-Glorana/Klara#19]
**Describe the bug**
Installer works but the program itself will not start even as administrator.

**To Reproduce**
1. Go to 'Task Bar'
2. Click on 'Klara'
4. See error 'Klara will not start'

**Expected behavior**
Klara starting.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: [Window 10]
 - Browser [Firefox]
 - Version [Version of what?]

**Additional context**
Installer worked fine but program itself will not start.
Running .Net 4.8
Tested on a Dell Inspiron 11-3162.  Did not work.
Tested on a Dell Inspiron 11-3185.  Did not work.
Pre Release 0.0.1 Alpha3 Pre Canadate tested and did not work.

**Comment by IM-studios** [comment]
Right here.

**Comment by carcarjg** [comment]
Dangit.

**Comment by IM-studios** [comment]
Hay one step at a time.  You "solved" the last problem and that is more than I could ever do.

**Comment by carcarjg** [comment]
Hmm, I have a feeling it might be linked with the last one.

**Comment by IM-studios** [comment]
Okay.  Step one.

**Comment by IM-studios** [comment]
Would it help if your program wrote crash reports that I could send you.

**Comment by carcarjg** [comment]
The installer currently is the default one with Visual Studio. I'm working on implementing logs in the program. It would be very helpful right now.

**Comment by IM-studios** [comment]
Okay.

**Comment by carcarjg** [comment]
Gladys being caught right now and not whenever we get to a few thousand lines of code.

**Comment by IM-studios** [comment]
yes.  As my Dad says "There is a time in the life of every problem were it is big enough to see and small enough to fix"

**Comment by IM-studios** [comment]
And right now it is small enough to fix.

**Comment by carcarjg** [comment]
Very true. I’m makeing a version right now that will spit out a txt file if it actually loads and makes it to the main script. That’s will be a temporary stand in for a log

**Comment by IM-studios** [comment]
Okay.  Just keep posting versions, and I will keep testing till it works.

**Comment by carcarjg** [comment]
Just published

**Comment by IM-studios** [comment]
Okay, testing.

**Comment by IM-studios** [comment]
Downloading.

**Comment by IM-studios** [comment]
I am switching in between modeling our assets and testing Klara

**Comment by IM-studios** [comment]
Extracting.

**Comment by carcarjg** [comment]
Nice

**Comment by IM-studios** [comment]
Installing.

**Comment by IM-studios** [comment]
Now what?

**Comment by carcarjg** [comment]
It should be in your start menu. I don’t remember if it auto starts

**Comment by IM-studios** [comment]
It will not start.

**Comment by carcarjg** [comment]
Hmm

**Comment by IM-studios** [comment]
What next?

**Comment by carcarjg** [comment]
Hang on. I’m looking through it real quick

**Comment by carcarjg** [comment]
Not in task manager?

**Comment by IM-studios** [comment]
No it is.

**Comment by carcarjg** [comment]
You can see it in task manager?

**Comment by IM-studios** [comment]
When I click on it I see the spinning blue thing over the mouse then nothing happens.

**Comment by carcarjg** [comment]
See if its installed in
C:\Users\YourUserName\AppData\Local\Apps\2.0\PCKO97LT.ZT2\L086GX29.A9T\klar..tion_0000000000000000_0000.0001_dfa9a878a6217cd8

**Comment by IM-studios** [comment]
oh task manager sorry. No

**Comment by IM-studios** [comment]
I thought you said task bar.

**Comment by IM-studios** [comment]
Yes it is installed.

**Comment by IM-studios** [comment]
In app data.

**Comment by carcarjg** [comment]
Oh? So it’s in the taskbar?

**Comment by IM-studios** [comment]
Yes.  Do you want a screen shot?

**Comment by carcarjg** [comment]
Sure

**Comment by IM-studios** [comment]
Okay.  Hold on.

**Comment by IM-studios** [comment]
![Klara](https://user-images.githubusercontent.com/63433840/79053760-4014b100-7c05-11ea-822f-3d6c5600792b.png)

**Comment by IM-studios** [comment]
Will that work?

**Comment by IM-studios** [comment]
![Klara](https://user-images.githubusercontent.com/63433840/79053788-6f2b2280-7c05-11ea-9307-417c46dbb34c.png)

**Comment by carcarjg** [comment]
Ok, so it installs properly. But doesn’t open....odd

**Comment by IM-studios** [comment]
Yes.

**Comment by carcarjg** [comment]
I think I found the problem. Uploading now

**Comment by carcarjg** [comment]
[klarasetup.zip](https://github.com/carcarjg/Klara/files/4465356/klarasetup.zip)

**Comment by IM-studios** [comment]
Okay, downloading.

**Comment by IM-studios** [comment]
Extracting.

**Comment by IM-studios** [comment]
Installing.

**Comment by IM-studios** [comment]
...........

**Comment by carcarjg** [comment]
.........?

**Comment by IM-studios** [comment]
It asked if I wanted to start Klara I said yes and nothing happend.

**Comment by carcarjg** [comment]
No admin prompt?

**Comment by IM-studios** [comment]
Just the swirly thing.

**Comment by IM-studios** [comment]
yes I got an admin prompt.

**Comment by IM-studios** [comment]
even as administrator.

**Comment by IM-studios** [comment]
you are getting closer.

**Comment by carcarjg** [comment]
I have no idea at this point. I’ll going to try a few thing on some blank vm’s stand by.

**Comment by IM-studios** [comment]
Standing by.  Maybe there is something wrong with my computer.  Do you have any other programs I can test?

**Comment by carcarjg** [comment]
Not in c# useing these library’s. I’ll see if I can wip up a quick test one.

**Comment by IM-studios** [comment]
Okay.

**Comment by IM-studios** [comment]
Hey I know this is off Klara but What do you think the roof should be?  threshed, wood shingles, metal, etc.

**Comment by IM-studios** [comment]
What is going on now?

**Comment by carcarjg** [comment]
Pain, a headache, rewriting a custom radio interface Library and tons of fun.

**Comment by IM-studios** [comment]
Yep you are experiencing the Bugged Code Nightmare.

**Comment by IM-studios** [comment]
I have had the same experience but with blender its called The Re-Topology Nightmare.

**Comment by carcarjg** [comment]
Yea I’ve had to do this a few times mainly v0.0.1 of my 
L1TmsDmi program, and any qt program ever

**Comment by carcarjg** [comment]
Loads of fun

**Comment by IM-studios** [comment]
Yep, like Christmas but a lot more fun.

**Comment by carcarjg** [comment]
Yep

**Comment by IM-studios** [comment]
Not to say that I am having a worse time than you but I have bean on the computer all afternoon trying to remodel the house.

-DELETE THIS MESSAGE-

**Comment by IM-studios** [comment]
Hey if you are still working on the Klara, you should take a brake and start again tomorrow.  Sometimes when I do that I have have a realization to fix the problem.

**Comment by carcarjg** [comment]
Yep, I’m working on some other things currently

**Comment by IM-studios** [comment]
Okay, good.

**Comment by IM-studios** [comment]
Well if you want to see were I have gotten on the house I can upload it to Git-Hub.

**Comment by carcarjg** [comment]
> Well if you want to see were I have gotten on the house I can upload it to Git-Hub.

Go for it

**Comment by IM-studios** [comment]
Okay.

**Comment by IM-studios** [comment]
just uploaded them.

**Comment by IM-studios** [comment]
Bug report updated after program was tested on two computers and did not work for both.

**Comment by IM-studios** [comment]
Bug report updated after Pre Release 0.0.1 Alpha3 Pre Canadate was tested and did not work.

**Comment by IM-studios** [comment]
Would it help if I took the source code and compiled it in visual studio for myself?

**Comment by IM-studios** [comment]
If I took the Klara source code.

**Comment by carcarjg** [comment]
Go ahead and try. It might work and it might not.

**Comment by carcarjg** [comment]
Wont fix tag added as Condition can not be replicated.
